### PR TITLE
Update glossary to latest spec

### PR DESCRIPTION
**Pull request by vr8hub**
I believe this is all correct. Around 200 of the entries were converted to endnotes. No errors on build, and what I looked at looks good in Books.

### CODE REVIEW

**Comment by acabal** [comment]
Sorry for the delay in this. I don't think we should cite  "the glossary" as the source for these endnotes. Who wrote the glossary? Was it Pollard? If so, then the cite should be `<cite>--Pollard</cite>`. It should be the actual author of the glosses.

**Comment by vr8hub** [comment]
We don’t know who wrote the glossary (it predates Pollard, although his introductory note says that it was expanded for this edition, but doesn’t say who did the expanding). And the glossary doesn’t have any citations. The only difference we made here was move something from one file (the glossary) to the another file (the endnotes). The only reason we need to say anything is to differentiate the endnotes from the actual text’s endnotes. We’re just saying where the definition came from, and it came from the glossary, which is all we know. It is a factual and informative statement; anything else we say is made up and misleading.

**Comment by acabal** [comment]
Yeah but saying "the glossary" doesn't say where the definition came from either. Sure it came from "the glossary" but is that in any way helpful as a citation? In any case if Pollard says his edition expands the glossary, then the expansions came from Pollard.

Given all that I think we should just remove the cites entirely. It's very very common for endnotes to include glosses like this without further comment. See Don Quixote for example. The average reader doesn't care who wrote the glosses or the endnotes; the existing endnotes are already meta-textual, made by an editor who I assume is Pollard; and Pollard already expanded the glossary with his own edits. If you want we can put it in the production notes that any glosses in the endnotes were repurposed from the glossary. Or, we can add an endnote in `bibliographical-note.xhtml` attached to `The restoration of obsolete words has necessitated a much fuller glossary`, that says something like: 

`For this edition glosses that only appear once in the work have been converted to endnotes. Any non-gloss endnotes are Pollard's --SE Editor`. 

I think that would work well.

**Comment by vr8hub** [comment]
Yes it does say where it came from — it came from the glossary. That’s all we know. And it’s all they know about the words that are still in the glossary. We didn’t say where the words came from when they were in the glossary, why do we suddenly have to say something just because they’re not in the glossary?
It is helpful because it differentiates the glossary endnotes from the non-glossary endnotes, which is all we’re after. We’re telling them the information we have—"hey, this definition came from the glossary, we just moved it to the endnote to make it easier for you.” Saying the endnote came from the glossary tells them all the information we have, and all the information they would have had if we’d left it in the glossary.
I understand it’s common for endnotes to include definitions, but those are typically from the same source, and these aren’t. Regardless, I don’t like adding endnotes from two different sources and not indicating which source the endnote is from. That implies authorship that is, again, incorrect. And the average reader may or may not care who wrote what in the glossary, but the important part is that the glossary doesn’t say. Therefore, there’s no reason to make up information for the endnotes. Especially since, again, we’re not doing so for the glossary itself.
The even more important part is that I care; I’m not going to imply that person A wrote something if person A did not in fact write that something.

I can live with removing the citations and putting an endnote in the bib note. It’s less clear that what is there now, but acceptable. I’ll do that later tonight.

**Comment by vr8hub** [comment]
Note added, citations removed.

**Comment by acabal** [comment]
Alright, excellent work. Thank you!

**Pull request merged**
